### ISSUE TITLE
Service fail

### ISSUE THREAD

**Issue by tomachalek** [czcorpus/klogproc#179]
```
panic: runtime error: index out of range [10] with length 10
bře 05 11:16:21 skalicka klogproc[2654174]: goroutine 283 [running]:
bře 05 11:16:21 skalicka klogproc[2654174]: klogproc/load/accesslog.(*LineParser).tokenize(0x46212e?, {0xc000366
bře 05 11:16:21 skalicka klogproc[2654174]:         /home/machalek/superhome/tools/klogproc/load/accesslog/parse
bře 05 11:16:21 skalicka klogproc[2654174]: klogproc/load/accesslog.(*LineParser).ParseLine(0xc0?, {0xc0003660c0
bře 05 11:16:21 skalicka klogproc[2654174]:         /home/machalek/superhome/tools/klogproc/load/accesslog/parse
bře 05 11:16:21 skalicka klogproc[2654174]: klogproc/conversion/mapka2.(*LineParser).ParseLine(0xc00033ec28?, {0
bře 05 11:16:21 skalicka klogproc[2654174]:         /home/machalek/superhome/tools/klogproc/conversion/mapka2/pa
bře 05 11:16:21 skalicka klogproc[2654174]: klogproc/load/batch.(*mapka2LineParser).ParseLine(0x7f0000000004?, {
bře 05 11:16:21 skalicka klogproc[2654174]:         /home/machalek/superhome/tools/klogproc/load/batch/parserFac
bře 05 11:16:21 skalicka klogproc[2654174]: main.(*tailProcessor).OnEntry(0xc00092c8f0, {0xc0003660c0?, 0xb5?}, 
bře 05 11:16:21 skalicka klogproc[2654174]:         /home/machalek/superhome/tools/klogproc/tailAction.go:97 +0x
bře 05 11:16:21 skalicka klogproc[2654174]: klogproc/load/tail.(*FileTailReader).ApplyNewContent(0xc0006be330, {
bře 05 11:16:21 skalicka klogproc[2654174]:         /home/machalek/superhome/tools/klogproc/load/tail/reader.go:
bře 05 11:16:21 skalicka klogproc[2654174]: klogproc/load/tail.Run.func1(0xc0006be330)
bře 05 11:16:21 skalicka klogproc[2654174]:         /home/machalek/superhome/tools/klogproc/load/tail/watchdog.g
bře 05 11:16:21 skalicka klogproc[2654174]: created by klogproc/load/tail.Run
bře 05 11:16:21 skalicka klogproc[2654174]:         /home/machalek/superhome/tools/klogproc/load/tail/watchdog.g
bře 05 11:16:21 skalicka systemd[1]: klogproc.service: Main process exited, code=exited, status=2/INVALIDARGUMEN
bře 05 11:16:21 skalicka systemd[1]: klogproc.service: Failed with result 'exit-code'.
bře 05 11:16:25 skalicka klogproc[2654188]: panic: runtime error: index out of range [10] with length 10
bře 05 11:16:25 skalicka klogproc[2654188]: goroutine 251 [running]:
bře 05 11:16:25 skalicka klogproc[2654188]: klogproc/load/accesslog.(*LineParser).tokenize(0x46212e?, {0xc00040a
bře 05 11:16:25 skalicka klogproc[2654188]:         /home/machalek/superhome/tools/klogproc/load/accesslog/parse
bře 05 11:16:25 skalicka klogproc[2654188]: klogproc/load/accesslog.(*LineParser).ParseLine(0xc0?, {0xc00040a0c0
bře 05 11:16:25 skalicka klogproc[2654188]:         /home/machalek/superhome/tools/klogproc/load/accesslog/parse
bře 05 11:16:25 skalicka klogproc[2654188]: klogproc/conversion/mapka2.(*LineParser).ParseLine(0xc0006ddc28?, {0
bře 05 11:16:25 skalicka klogproc[2654188]:         /home/machalek/superhome/tools/klogproc/conversion/mapka2/pa
bře 05 11:16:25 skalicka klogproc[2654188]: klogproc/load/batch.(*mapka2LineParser).ParseLine(0x6?, {0xc00040a0c
bře 05 11:16:25 skalicka klogproc[2654188]:         /home/machalek/superhome/tools/klogproc/load/batch/parserFac
bře 05 11:16:25 skalicka klogproc[2654188]: main.(*tailProcessor).OnEntry(0xc000294d00, {0xc00040a0c0?, 0xb5?}, 
bře 05 11:16:25 skalicka klogproc[2654188]:         /home/machalek/superhome/tools/klogproc/tailAction.go:97 +0x
bře 05 11:16:25 skalicka klogproc[2654188]: klogproc/load/tail.(*FileTailReader).ApplyNewContent(0xc0006362a0, {
bře 05 11:16:25 skalicka klogproc[2654188]:         /home/machalek/superhome/tools/klogproc/load/tail/reader.go:
bře 05 11:16:25 skalicka klogproc[2654188]: klogproc/load/tail.Run.func1(0xc0006362a0)
bře 05 11:16:25 skalicka klogproc[2654188]:         /home/machalek/superhome/tools/klogproc/load/tail/watchdog.g
bře 05 11:16:25 skalicka klogproc[2654188]: created by klogproc/load/tail.Run
bře 05 11:16:25 skalicka klogproc[2654188]:         /home/machalek/superhome/tools/klogproc/load/tail/watchdog.g
bře 05 11:16:25 skalicka systemd[1]:
```

**Comment by tomachalek** [comment]
Improved klogproc now reports a suspicious line:

```json
{"level":"error","line":"199.21.113.77 - - 05/Mar/2023:10:02:45 +0100  POST /general/index/UploadFile.php?m=uploadPicture&uploadType=eoffice_logo&userId= HTTP/1.1\" 400 182","time":"2023-03-05T11:47:25+01:00","message":"Apache log tokenizer failed to process line"}
{"level":"warn","error":"failed to get token [10] (num. available: [10]): LineParsingError at line -1","time":"2023-03-05T11:47:25+01:00","message":"parsing error in file /var/log/nginx/korpus.cz/access.log"}
```
